name: super_senha

description: Jogo de adivinhação de palavras de 5 letras.

publish_to: "none"

version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/words.json
    - assets/splash_screen.png
    - assets/icon.png
    - assets/play_icon.png
    - assets/help_icon.png
    - assets/settings_icon.png
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/splash_screen.png
  color: "#121212"
  fullscreen: true
